### ISSUE TITLE
SpaceNavigator TODO tasks

### ISSUE THREAD

**Issue by PeterBowman** [roboticslab-uc3m/yarp-devices#110]
- [x] Fix intermittency in data acquisition (see attached screenshot)
- [x] Move configuration parameters to .ini file
- [ ] Use color-debug macros or remove existing includes
- [ ] Let users compile with X11 (Unix)
- [ ] FindSpnav.cmake could look for official 3DX driver (Unix)
- [ ] Add Windows support
- [ ] Add Doxygen documentation
- [x] Document plugin & dependencies (install guides)
- [ ] Rename plugin (the [`libspnav`](http://spacenav.sourceforge.net/) library actually gives support to a wider range of products)
- [x] Re-implement as `yarp::dev::IJoypadController`? https://github.com/roboticslab-uc3m/yarp-devices/issues/265
- [ ] Review chosen coordinates (https://github.com/roboticslab-uc3m/yarp-devices/commit/3e78ed1bbc3f3814b9d4066fb56f3daa703984b5), apply isometric view?

**Comment by PeterBowman** [comment]
![cropped](https://cloud.githubusercontent.com/assets/9977198/24450902/012ca4a4-147d-11e7-95a0-fba59b6d3ce1.png)

**Comment by PeterBowman** [comment]
> * Fix intermittency in data acquisition (see attached screenshot)

Fixed in https://github.com/roboticslab-uc3m/yarp-devices/commit/566ec8b813994359c3e20094c8f3eb659f6f2690.

> * Move configuration parameters to .ini file

Probably meant to expose those parameters via CLI/.ini. Done long ago, and recently enhanced with the new YARP's parameter parsing from .md files mechanism ([config](https://github.com/roboticslab-uc3m/yarp-devices/blob/eb1bfdf1c151fd587d253a9b56d37083e0155e01/libraries/YarpPlugins/SpaceNavigator/SpaceNavigator_params.md)).

> * Use color-debug macros or remove existing includes

Replaced with YARP logging goodies, see https://github.com/roboticslab-uc3m/questions-and-answers/issues/90.

> * Let users compile with X11 (Unix)

The X11 magellan API "only supports a limited subset of features. Basically just receiving input events and changing sensitivity, no queries, device information, or configuration management." ([source](https://github.com/FreeSpacenav/libspnav/blob/bcc2e295d156cceaa0c48911251cbffa09e8c626/README.md)). I don't think we want this.

> * FindSpnav.cmake could look for official 3DX driver (Unix)

[Quote](https://github.com/FreeSpacenav/libspnav/blob/bcc2e295d156cceaa0c48911251cbffa09e8c626/doc/manual.md):

> Since the 3Dconnexion driver is practically unmaintained for the last decade, and never really worked very well to begin with (which was what led to the development of spacenavd), and also since the magellan protocol introduces an unnecessary dependency to the X window system, and provides very rudimentary functionality, new applications are encouraged to use spnav_open.

Nah, we don't want this either.

> * Add Windows support

Who cares about Windows? Besides, WSL won't do either, doesn't seem to detect the USB device.

> * Add Doxygen documentation

Less is better, compare other devices.

> * Document plugin & dependencies (install guides)

There was an attempt: [README.md](https://github.com/roboticslab-uc3m/yarp-devices/blob/eb1bfdf1c151fd587d253a9b56d37083e0155e01/libraries/YarpPlugins/SpaceNavigator/README.md).

> * Rename plugin (the [`libspnav`](http://spacenav.sourceforge.net/) library actually gives support to a wider range of products)

Version 1.0 of libspnav allows querying the device type ([source](https://github.com/FreeSpacenav/libspnav/blob/bcc2e295d156cceaa0c48911251cbffa09e8c626/src/spnav.h#L225-L252)). For now, we could only test the library with the Space Navigator (old) and SpaceMouse Compact (new) joysticks. I'd keep the current "SpaceNavigator" name as a reference to the underlying library.

> * Review chosen coordinates ([3e78ed1](https://github.com/roboticslab-uc3m/yarp-devices/commit/3e78ed1bbc3f3814b9d4066fb56f3daa703984b5)), apply isometric view?

To avoid confusion, I have dropped the misleading roll-pitch-yaw notation in the source code. While axis mappings probably can be tweaked via daemon configuration ([ref](https://github.com/FreeSpacenav/libspnav/blob/bcc2e295d156cceaa0c48911251cbffa09e8c626/src/spnav.h#L350-L351)), we can keep the hardcoded defaults used so far, until support needs to be included for additional libspnav-based devices.
